
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>

CONSTRUCT
  {
    ?games wdt:P156 ?games_next. 
  }
WHERE
  { SERVICE <x-sparql-anything:location=../Input/RelationsAcrossRows-preprocessed.csv,csv.headers=true> {
fx:properties  fx:csv.null-string  "" .
        ?c        xyz:GameID1 ?GameID1;
		  xyz:GameID2 ?GameID2.
}
BIND (URI(CONCAT('http://www.wikidata.org/entity/', ?GameID1)) AS ?games)
BIND (URI(CONCAT('http://www.wikidata.org/entity/', ?GameID2)) AS ?games_next)
 
  }

