
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>



CONSTRUCT {
	?candidate wdt:P102 ?party. 
	
}
FROM <file:../Input/simpleMapping.csv>
WHERE {
  BIND (URI(CONCAT('http://www.wikidata.org/entity/', ?Candidate)) AS ?candidate)
  BIND (URI(CONCAT('http://www.wikidata.org/entity/', ?2_Party)) AS ?party)
}



